# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ComputationalDataAPI_pb2 as ComputationalDataAPI__pb2


class ComputationalDataAPIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createComputationalDataProduct = channel.unary_unary(
                '/ComputationalDataAPIService/createComputationalDataProduct',
                request_serializer=ComputationalDataAPI__pb2.ComputationalDataProduct.SerializeToString,
                response_deserializer=ComputationalDataAPI__pb2.CompDataProductCreateResponse.FromString,
                )


class ComputationalDataAPIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createComputationalDataProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationalDataAPIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createComputationalDataProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.createComputationalDataProduct,
                    request_deserializer=ComputationalDataAPI__pb2.ComputationalDataProduct.FromString,
                    response_serializer=ComputationalDataAPI__pb2.CompDataProductCreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ComputationalDataAPIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComputationalDataAPIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createComputationalDataProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ComputationalDataAPIService/createComputationalDataProduct',
            ComputationalDataAPI__pb2.ComputationalDataProduct.SerializeToString,
            ComputationalDataAPI__pb2.CompDataProductCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
